### ISSUE TITLE
Use double versions of math.h functions

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/RZIntrinsicContentSizeTextView#5]
Xcode 6.3 turned on stricter default warnings, so now `fabsf` and its ilk cause warnings. We should be using `fabs` and the other versions of these methods that take `double` instead of `float`.

**Comment by joshavant** [comment]
In the current version, using Xcode 7.2, I'm currently getting this compiler warning:
`Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value`
for this line:
https://github.com/Raizlabs/RZIntrinsicContentSizeTextView/blob/master/Pod/Classes/RZIntrinsicContentSizeTextView.m#L395

**Comment by ZevEisenberg** [comment]
@joshavant mind submitting a PR?

**Comment by ZevEisenberg** [comment]
Actually, I think this was already fixed in https://github.com/Raizlabs/RZIntrinsicContentSizeTextView/pull/8, and we just need a new release. @dostrander would you do the honors?

**Comment by dostrander** [comment]
@ZevEisenberg @joshavant published a new release (0.1.1)
